version: '2'
services:
  db:
    image: couchdb:1.6
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdb
    volumes_from:
      - dbdata

  # for persistance of database data
  dbdata:
    image: couchdb:1.6
    volumes:
      - /var/lib/couchdb
    command: "true"

  web:
    image: etheroscope
    command: mix do deps.get, phx.server
    links:
      - "db:db"
    environment:
      - MIX_ENV
    volumes:
      - .:/app
    ports:
      - "4000:4000"
